export const PlayersLargeConfig = {
  columns: [
    {
      dataField: 'web_name',
      caption: 'Name',
      width: 120,
      dataType: 'text',
      visible: true,
      visibleIndex: 1,
    },
    {
      dataField: 'teamInfo',
      caption: 'Club',
      width: 95,
      dataType: 'text',
      visible: true,
      visibleIndex: 2,
    },
    {
      dataField: 'elementTypeInfo',
      caption: 'Position',
      width: 120,
      dataType: 'text',
      visible: true,
      visibleIndex: 3,
    },
    {
      dataField: 'current_cost',
      caption: 'Cost',
      width:95,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 4,
    },
    {
      dataField: 'chance_of_playing_this_round',
      caption: 'Appearance chance',
      width: 220,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'chance_of_playing_next_round',
      caption: 'Next Week Appearance chance',
      width: 310,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'ep_next',
      caption: 'Next Week Expected Points',
      width: 300,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'ep_this',
      caption: 'xPts',
      width: 91,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 7,
    },
    {
      dataField: 'event_points',
      caption: 'Previous Week Pts',
      width: 210,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'form',
      caption: 'Form',
      width: 96,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 5,
    },
    {
      dataField: 'points_per_game',
      caption: 'Pts/Game',
      width: 135,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 8,
    },
    {
      dataField: 'selected_by_percent',
      caption: 'Squad Selection',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'total_points',
      caption: 'Total Pts',
      width: 126,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 10,
    },
    {
      dataField: 'transfers_in',
      caption: 'Transfers In',
      width: 160,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'transfers_out',
      caption: 'Transfers Out',
      width: 170,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'value_form',
      caption: 'Form Value',
      width: 150,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'value_season',
      caption: 'Cost Value',
      width: 150,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'minutes',
      caption: 'Total minutes',
      width: 170,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'goals_scored',
      caption: 'Goals',
      width: 102,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 11,
    },
    {
      dataField: 'assists',
      caption: 'Assists',
      width: 115,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 12,
    },
    {
      dataField: 'clean_sheets',
      caption: 'Clean sheets',
      width: 170,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 13,
    },
    {
      dataField: 'news',
      caption: 'Player News',
      width: 500,
      dataType: 'text',
      visible: true,
      visibleIndex: 17,
    },
    {
      dataField: 'goals_conceded',
      caption: 'Goals Conceded',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'penalties_saved',
      caption: 'Penalties saved',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'penalties_missed',
      caption: 'Penalties missed',
      width: 200,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'yellow_cards',
      caption: 'Yellow cards',
      width: 160,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'red_cards',
      caption: 'Red cards',
      width: 140,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'saves',
      caption: 'Saves',
      width: 120,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'bonus',
      caption: 'Total Bonus Points',
      width: 210,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'bps',
      caption: 'Total Bonus Point System',
      width: 260,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'influence_rank',
      caption: 'FPL Influence Rank',
      width: 210,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'creativity_rank',
      caption: 'FPL Creativity Rank',
      width: 220,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'threat_rank',
      caption: 'FPL Goal Threat Rank',
      width: 230,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'ict_index_rank',
      caption: 'FPL ICT Index Rank',
      width: 210,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'corners_and_indirect_freekicks_order',
      caption: 'Corners Order',
      width: 180,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'direct_freekicks_order',
      caption: 'Free Kick Order',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'penalties_order',
      caption: 'Penalties Order',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
  ]
}

export const PlayersXSmallConfig = {
  columns: [
    {
      dataField: 'web_name',
      caption: 'Name',
      width: 95,
      dataType: 'text',
      visible: true,
      visibleIndex: 1,
    },
    {
      dataField: 'teamInfo',
      caption: 'Club',
      width: 87,
      dataType: 'text',
      visible: true,
      visibleIndex: 2,
    },
    {
      dataField: 'elementTypeInfo',
      caption: 'Position',
      width: 110,
      dataType: 'text',
      visible: true,
      visibleIndex: 3,
    },
    {
      dataField: 'current_cost',
      caption: 'Cost',
      width: 87,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 4,
    },
    {
      dataField: 'chance_of_playing_this_round',
      caption: 'Appearance chance',
      width: 220,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'chance_of_playing_next_round',
      caption: 'Next Week Appearance chance',
      width: 310,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'ep_next',
      caption: 'Next Week Expected Points',
      width: 300,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'ep_this',
      caption: 'xPts',
      width: 85,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 7,
    },
    {
      dataField: 'event_points',
      caption: 'Previous Week Pts',
      width: 210,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'form',
      caption: 'Form',
      width: 90,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 5,
    },
    {
      dataField: 'points_per_game',
      caption: 'Pts/Game',
      width: 122,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 8,
    },
    {
      dataField: 'selected_by_percent',
      caption: 'Squad Selection',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'total_points',
      caption: 'Total Pts',
      width: 126,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 10,
    },
    {
      dataField: 'transfers_in',
      caption: 'Transfers In',
      width: 160,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'transfers_out',
      caption: 'Transfers Out',
      width: 170,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'value_form',
      caption: 'Form Value',
      width: 150,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'value_season',
      caption: 'Cost Value',
      width: 150,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'minutes',
      caption: 'Total minutes',
      width: 170,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'goals_scored',
      caption: 'Goals',
      width: 102,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 11,
    },
    {
      dataField: 'assists',
      caption: 'Assists',
      width: 115,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 12,
    },
    {
      dataField: 'clean_sheets',
      caption: 'Clean sheets',
      width: 170,
      dataType: 'numeric',
      visible: true,
      visibleIndex: 13,
    },
    {
      dataField: 'news',
      caption: 'Player News',
      width: 500,
      dataType: 'text',
      visible: true,
      visibleIndex: 17,
    },
    {
      dataField: 'goals_conceded',
      caption: 'Goals Conceded',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'penalties_saved',
      caption: 'Penalties saved',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'penalties_missed',
      caption: 'Penalties missed',
      width: 200,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'yellow_cards',
      caption: 'Yellow cards',
      width: 160,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'red_cards',
      caption: 'Red cards',
      width: 140,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'saves',
      caption: 'Saves',
      width: 120,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'bonus',
      caption: 'Total Bonus Points',
      width: 210,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'bps',
      caption: 'Total Bonus Point System',
      width: 260,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'influence_rank',
      caption: 'FPL Influence Rank',
      width: 210,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'creativity_rank',
      caption: 'FPL Creativity Rank',
      width: 220,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'threat_rank',
      caption: 'FPL Goal Threat Rank',
      width: 230,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'ict_index_rank',
      caption: 'FPL ICT Index Rank',
      width: 210,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'corners_and_indirect_freekicks_order',
      caption: 'Corners Order',
      width: 180,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'direct_freekicks_order',
      caption: 'Free Kick Order',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
    {
      dataField: 'penalties_order',
      caption: 'Penalties Order',
      width: 190,
      dataType: 'numeric',
      visible: false,
    },
  ]
}