export const PastSeasonMidConfig = {
    columns: [
      {
        dataField: 'season_name',
        caption: 'Season',
        width: 100,
        dataType: 'text',
        visible: true,
        visibleIndex: 1,
      },
      {
        dataField: 'total_points',
        caption: 'Pts',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 2,
      },
      {
        dataField: 'starts',
        caption: 'Starts',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 3,
      },
      {
        dataField: 'minutes',
        caption: 'Minutes',
        width:50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 4,
      },
      {
        dataField: 'goals_scored',
        caption: 'Goals',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 5,
      },
      {
        dataField: 'assists',
        caption: 'Assists',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 6,
      },
      {
        dataField: 'expected_goals',
        caption: 'xG',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 7,
      },
      {
        dataField: 'expected_assists',
        caption: 'xA',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 8,
      },
      {
        dataField: 'clean_sheets',
        caption: 'Clean sheets',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 9,
      },
      {
        dataField: 'yellow_cards',
        caption: 'Yellow Cards',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 10,
      },
      {
        dataField: 'red_cards',
        caption: 'Red Cards',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 11,
      },
      {
        dataField: 'bonus',
        caption: 'Bonus Points',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 12,
      },
      {
        dataField: 'bps',
        caption: 'Bonus PS',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 13,
      },
      {
        dataField: 'influence',
        caption: 'I',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 14,
      },
      {
        dataField: 'creativity',
        caption: 'C',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 15,
      },
      {
        dataField: 'threat',
        caption: 'T',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 16,
      },
      {
        dataField: 'ict_index',
        caption: 'ICT',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 16,
      },
    ]
  }

  export const FixtureConfig = {
    columns: [
      {
        dataField: 'kickoff_time',
        caption: 'Date',
        width: 300,
        dataType: 'text',
        visible: true,
        visibleIndex: 1,
      },
      {
        dataField: 'event',
        caption: 'GW',
        width: 50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 2,
      },
      {
        dataField: 'away',
        caption: 'Opponent',
        width: 250,
        dataType: 'text',
        visible: true,
        visibleIndex: 3,
      },
      {
        dataField: 'difficulty',
        caption: 'FDR',
        width:50,
        dataType: 'numeric',
        visible: true,
        visibleIndex: 4,
      },
    ]
  }